### ISSUE TITLE
Can we add "[UserSettings]" in the latest patch?

### ISSUE THREAD

**Issue by DoubleTrust** [Lyall/WukongTweak#2]
I found that the config file lastest release patch no longer has "[UserSettings]", which could be seen in previous projects:
<img width="938" alt="image" src="https://github.com/user-attachments/assets/7f2552f2-9475-49ce-9957-934effab74e7">
<img width="984" alt="image" src="https://github.com/user-attachments/assets/6ca68b31-e69b-4ddc-8255-b57b496839f1">

So can we define the resolution manually to make it work in 16:10 screen display? I found that it cannot work to disbale ratio limit and extend FOV at the same time with 16:10 display.

**Comment by Lyall** [comment]
That section is from SUWSF. That value is only used for calculations in the patches themselves. The previous patch I had put up used this software to patch sections of the game's memory. With this new standalone fix there is no resolution entry and no part of WukongTweak adjusts game resolution (yet).

There are some considerations I'd like to make for <16:9 (16:10, 4:3 etc) like expanding the FOV instead of cropping it horizontally, but I need some time to look into it.

**Comment by DoubleTrust** [comment]
> That section is from SUWSF. That value is only used for calculations in the patches themselves. The previous patch I had put up used this software to patch sections of the game's memory. With this new standalone fix there is no SUWSF and thus no resolution entry, and no part of WukongTweak adjusts game resolution (yet).
> 
> There are some considerations I'd like to make for <16:9 (16:10, 4:3 etc) like expanding the FOV instead of cropping it horizontally, but I need some time to look into it.

Thank you for your response. Looking forward to seeing the latest patch!

**Comment by Lyall** [comment]
Added fix for cropped FOV at <16:9 in v0.8.2
